# Harmful gases and the effect on the temperature as years preceeds (Global Warming)

Author: Toshiki Kobayashi

Course Project, UC Irvine, June 3, Spring 2026

## Questions to be answered before you submit your project.

* What is your Student ID number?
45842029



* What is the "extra component" (or multiple extra components) that you're including in this project that weren't covered in Math 10?

K-Nearest-Neighbors Regression

- Do you allow me to share your project with future Math 10 students as their references? (optional)

No

* If a lot of your knowledge of Python comes from somewhere outside of Math 10 (e.g., you took another Python class before), tell me a little about that.  (This way, if your project looks significantly different from what we learned in Math 10, this explanation will help me understand why.)

I do leetcode in python on my free time, so some methods may have influence from that

## Introduction

My project will be examining if harmful gases such as Carbon dioxide, Methane gas, and Nitrogen gas has an effect on the overall difference in the global temperature. I would also be training data to calculate the predicted change in temperature over years of time. Lastly, I would also be training data to calculate predicted differences in temperatures using K-Neighbor Regression. This is to see if global warming is a problem or not due to the effects of harmful gasses.

## Cleaning and Understanding the Data
Here we will try to clean the data so it can be used for testing and regression. We will also be understanding the data and what each column represents in the dataset.

First, import pandas to read the csv file as a dataframe

In [1]:
import pandas as pd

In [2]:
df_imported = pd.read_csv("climate_change.csv")
df_imported

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
0,1983,5,2.556,345.96,1638.59,303.677,191.324,350.113,1366.1024,0.0863,0.109
1,1983,6,2.167,345.52,1633.71,303.746,192.057,351.848,1366.1208,0.0794,0.118
2,1983,7,1.741,344.15,1633.22,303.795,192.818,353.725,1366.2850,0.0731,0.137
3,1983,8,1.130,342.25,1631.35,303.839,193.602,355.633,1366.4202,0.0673,0.176
4,1983,9,0.428,340.17,1648.40,303.901,194.392,357.465,1366.2335,0.0619,0.149
...,...,...,...,...,...,...,...,...,...,...,...
303,2008,8,-0.266,384.15,1779.88,321.405,244.200,535.072,1365.6570,0.0036,0.407
304,2008,9,-0.643,383.09,1795.08,321.529,244.083,535.048,1365.6647,0.0043,0.378
305,2008,10,-0.780,382.99,1814.18,321.796,244.080,534.927,1365.6759,0.0046,0.440
306,2008,11,-0.621,384.13,1812.37,322.013,244.225,534.906,1365.7065,0.0048,0.394
307,2008,12,-0.666,385.56,1812.88,322.182,244.204,535.005,1365.6926,0.0046,0.330

What are the columns we are working with?

In [3]:
df_imported.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      308 non-null    int64
 1   Month     308 non-null    int64
 2   MEI       308 non-null    float64
 3   CO2       308 non-null    float64
 4   CH4       308 non-null    float64
 5   N2O       308 non-null    float64
 6   CFC-11    308 non-null    float64
 7   CFC-12    308 non-null    float64
 8   TSI       308 non-null    float64
 9   Aerosols  308 non-null    float64
 10  Temp      308 non-null    float64
dtypes: float64(9), int64(2)
memory usage: 26.6 KB

Now, we drop unnecessary data that we will not be using for predicting values using regression

In [4]:
df = df_imported.drop(["Month","MEI","CFC-11", "CFC-12", "TSI","Aerosols"], axis = 1)
df.head()

   Year     CO2      CH4      N2O   Temp
0  1983  345.96  1638.59  303.677  0.109
1  1983  345.52  1633.71  303.746  0.118
2  1983  344.15  1633.22  303.795  0.137
3  1983  342.25  1631.35  303.839  0.176
4  1983  340.17  1648.40  303.901  0.149

As you can see from the code below, all columns in the dataframe do not have any missing data so `dropna()` is uneccessary

In [5]:
df.isna().any(axis=1).sum()

0

However, we will just do `dropna()` just in case

In [6]:
df = df.dropna()

Lets examine our new data frame with only columns we are working with

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    308 non-null    int64
 1   CO2     308 non-null    float64
 2   CH4     308 non-null    float64
 3   N2O     308 non-null    float64
 4   Temp    308 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 12.2 KB

There are no null values in each columns. The data types are present and there are no "object" datatypes.

What is the range of each colmns we are working with?

In [8]:
df["Year"].unique()

array([1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008])

This data, in terms of year, is from 1983 to 2008, which is a bit old from the current year, 2026, but we can still run regressions and tests

Lets look at the other columns in the data sets

In [9]:
df.describe()

              Year         CO2          CH4         N2O        Temp
count   308.000000  308.000000   308.000000  308.000000  308.000000
mean   1995.662338  363.226753  1749.824513  312.391834    0.256776
std       7.423197   12.647125    46.051678    5.225131    0.179090
min    1983.000000  340.170000  1629.890000  303.677000   -0.282000
25%    1989.000000  353.020000  1722.182500  308.111500    0.121750
50%    1996.000000  361.735000  1764.040000  311.507000    0.248000
75%    2002.000000  373.455000  1786.885000  316.979000    0.407250
max    2008.000000  388.500000  1814.180000  322.182000    0.739000

The harmful gases we will be working with are `CO2`(Carbon dioxide), `CH4`(Methane Gas), and `N2O`(Nitrogen gas). The gases' concentrations are in the units of ppmv.
The temperatures is the difference in degrees Celcius between the average global temperature (all of this was described in the website, *Kaggle*, I took the dataset from linked at the bottom) https://www.kaggle.com/datasets/econdata/climate-change

`CO2` ranges from 340.17 ppmv to 388.5 ppmv
`CH4` ranges from 1629.89 ppmv to 1814.18 ppmv
`N2O` ranges from 303.677 ppmv to 322.182 ppmv
`Temp` ranges from -0.282 C to 0.739 C

## Linear Regression
Here we will try to find the best fit a linear regression model using `CO2`(Carbon dioxide), `CH4`(Methane Gas), and `N2O`(Nitrogen gas) to predict `Temp` values

First import `LinearRegression` from sklearn and we instanciate it using `reg` as the vaiable name

In [10]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

Now, we fit the model using `CO2`, `CH4`, `N2O` to predict `Temp` values

In [11]:
cols = ["CO2", "CH4", "N2O"]
reg.fit(df[cols], df["Temp"])
df["predict_temp"] = reg.predict(df[cols])

Lets check the accuracy of our prediction using Mean Squared Error (MSE) and Mean Absolute (MAE)

In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(df["Temp"], df["predict_temp"])

0.013763447425201211

In [13]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(df["Temp"], df["predict_temp"])

0.09135447842037007

As you can see above, the linear regression model is pretty accurate due to the low errors obtained from both the MSE and MAE

Lets check the values of both the intercept and the coefficent to have an understanding of the relationship between `CO2`, `CH4`, `N2O` that predict `Temp` values

In [14]:
reg.intercept_

-4.2676861582111405

In [15]:
reg.coef_

array([0.00768481, 0.00073491, 0.00143143])

The inetercept starts from negative since all of the data does not start from 0.
However, every coefficent in the model has a positive value meaning an increase in `CO2`, `CH4`, `N2O` has an increase in `Temp` values

We can visualize the graph of the relationship using altair between the actual relationship between `CO2`, `CH4`, `N2O` and `Temp` and compare it with `CO2`, `CH4`, `N2O` and `predict_temp` one column at a time

In [16]:
import altair as alt

In [17]:
Carbon_chart = alt.Chart(df).mark_circle(color="red").encode(
    x = alt.X("CO2", scale = alt.Scale(zero=False)),
    y = alt.Y("Temp", scale = alt.Scale(zero=False))
)
Methane_chart = alt.Chart(df).mark_circle(color="blue").encode(
    x = alt.X("CH4", scale = alt.Scale(zero=False)),
    y = alt.Y("Temp", scale = alt.Scale(zero=False))
)
Nitrogen_chart = alt.Chart(df).mark_circle(color="green").encode(
    x = alt.X("N2O", scale = alt.Scale(zero=False)),
    y = alt.Y("Temp", scale = alt.Scale(zero=False))
)

Linear_Carbon_chart = alt.Chart(df).mark_circle(color="red").encode(
    x = alt.X("CO2", scale = alt.Scale(zero=False)),
    y = alt.Y("predict_temp", scale = alt.Scale(zero=False))
)
Linear_Methane_chart = alt.Chart(df).mark_circle(color="blue").encode(
    x = alt.X("CH4", scale = alt.Scale(zero=False)),
    y = alt.Y("predict_temp", scale = alt.Scale(zero=False))
)
Linear_Nitrogen_chart = alt.Chart(df).mark_circle(color="green").encode(
    x = alt.X("N2O", scale = alt.Scale(zero=False)),
    y = alt.Y("predict_temp", scale = alt.Scale(zero=False))
)

Carbon_chart & Linear_Carbon_chart| Methane_chart & Linear_Methane_chart|  Nitrogen_chart & Linear_Nitrogen_chart

alt.HConcatChart(...)

The original graphs (top) of the actual relationship between `CO2`, `CH4`, `N2O` and `Temp` looks scattered and hard to understand but after fitting the data, it is clear that the predicted relationship between `CO2`, `CH4`, `N2O` and `predict_temp` is linearly increasing.

## Polynomial Regression (machine learning)
Here we will try to find if as the year goes on, the temperature also rises due to the factors of the harmful gases. However, we will be training the data using train test split method for machine learning

Lets look at the graph to determine which degree to use

In [18]:
Year_chart = alt.Chart(df).mark_circle(color="red").encode(
    x = alt.X("Year", scale = alt.Scale(zero=False)),
    y = alt.Y("Temp", scale = alt.Scale(zero=False))
)
Year_chart

alt.Chart(...)

Looks like a degree of 3 will look good since the graph looks like it goes down at the start and starts increasing then decrases a bit at the end

First import `PolynomialFeatures` from sklearn and create the polynomial graph in the degree of 3

In [19]:
from sklearn.preprocessing import PolynomialFeatures

In [20]:
deg = 3
poly = PolynomialFeatures(degree = deg, include_bias = False)
year = pd.DataFrame(poly.fit_transform(df[["Year"]]))
year.columns = poly.get_feature_names_out()

Then, import the `train_test_split` from sklearn to train and test the data

In [21]:
from sklearn.model_selection import train_test_split

We are going to use the default train test split sizes which are 80% train and 20% test split. Then fit the data using `X_train` and `y_train`

In [22]:
seed = 1234
X_train, X_test, y_train, y_test = train_test_split(year, df["Temp"], random_state = seed)
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

Now, we are going to predict the data using X_test and X_train, and see its accuracy using Mean Squared Error

In [23]:
y_pred_train = reg.predict(X_train)
mean_squared_error(y_pred_train, y_train)

0.013211888552188574

In [24]:
y_pred_test = reg.predict(X_test)
mean_squared_error(y_pred_test, y_test)

0.01006960591460284

The degree of 3 has a pretty accurate fit since the training error and especially the testing error has a very low value.

Now we are going to examine the intercepts and coefficents of the graph to see if the graph was overfitted or not

In [25]:
reg.intercept_

764437.5011252676

In [26]:
reg.coef_

array([-1.14999605e+03,  5.76658930e-01, -9.63850932e-05])

The coef for index 1 and 2 above for each coefficent is pretty low. However, as we learned both of these values are being multiplied by the year raised to some power so, the low values of the coefficents makes sense. So, the graph was not overfitted.

Now, we are going to visualize and compare the predicted increase in temperature values with the actual increase temperature values as Years go on

In [27]:
import numpy as np

In [28]:
x_year = np.arange(min(df["Year"]), max(df["Year"]), 0.1)
df_poly = pd.DataFrame(
    {
        "x_year":x_year
    }
)

Here, we are calculating each predicted value of `y_pred_temp` using each value in `x_year` to show the relationship between year and predicted temperature

In [29]:
df_poly["y_pred_temp"] = reg.intercept_ 
for d in range(0,deg):
    df_poly["y_pred_temp"] += reg.coef_[d]*df_poly["x_year"]**(d+1)

In [30]:
poly_chart = alt.Chart(df_poly).mark_line().encode(
    x = alt.X("x_year", scale = alt.Scale(zero=False)),
    y = alt.Y("y_pred_temp", scale = alt.Scale(zero=False))
)
Year_chart + poly_chart

alt.LayerChart(...)

However the graph shows that a fairly polynomial relation with slight curves. It looks like we were sucessfully able to fit a polynomial graph by training our data by using degree of 3 polynomial without overfitting or underfitting the data

## K-Neighbors Regression (extra)
Lastly, we will run K-neighbors regression to predict the value of difference temperature using `CO2`, `CH4`, `N2O`

First, we train the data by performing a train test split using the default 80% train and 20% test split (remember `seed` is from the same random state number as the seed used for train test split in polynomial regression)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df[cols], df["Temp"], random_state = seed)

Now we import `KNeighborsRegressor` and instaciate it using `knn` with 10 neighbors
Then we fit the data using `X_train` and `y_train`

In [32]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors = 10)
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=10)

Lets predict the change in temperature and evalutate the error using MSE

In [33]:
df["K_predict_temp"] = knn.predict(df[cols])
mean_squared_error(df["Temp"], df["K_predict_temp"])

0.010000169935064935

The error seems pretty low, which means we were sucessfully able to predict values by fitting `X_train` and `y_train`

Lets compare the actual graph with the predicted graph again to see how well the training data fitted

In [34]:
K_neighbor_Carbon_chart = alt.Chart(df).mark_circle(color="red").encode(
    x = alt.X("CO2", scale = alt.Scale(zero=False)),
    y = alt.Y("K_predict_temp", scale = alt.Scale(zero=False))
)
K_neighbor_Methane_chart = alt.Chart(df).mark_circle(color="blue").encode(
    x = alt.X("CH4", scale = alt.Scale(zero=False)),
    y = alt.Y("K_predict_temp", scale = alt.Scale(zero=False))
)
K_neighbor_Nitrogen_chart = alt.Chart(df).mark_circle(color="green").encode(
    x = alt.X("N2O", scale = alt.Scale(zero=False)),
    y = alt.Y("K_predict_temp", scale = alt.Scale(zero=False))
)

Carbon_chart & K_neighbor_Carbon_chart| Methane_chart & K_neighbor_Methane_chart| Nitrogen_chart & K_neighbor_Nitrogen_chart

alt.HConcatChart(...)

The original charts (top) are the relationship between `CO2`, `CH4`, `N2O` and `Temp` and the bottom charts (bottom) are the relationship between `CO2`, `CH4`, `N2O` and `K_predict_temp`. Both charts look scattered but the K neighbor regression chart looks more compact compared to the original graph. I would say that the k neighbor regression was sucessful at generalizing the apperent positive relationship between harmful gases and temperature.

## Summary

In this project we have found out that due to the concentrations of harmful gases, there is an increase in global temperature overtime by running linear regression. We were also able to train data using our knowledge of machine learning and fit using polynomial regression to predict values. Lastly, we did Kneighbor regression to predict temperture values using concentrations of harmful gases. In all regressions we found a low mean squared error meaning we were able to sucessfully, able to predict differences in temperature values using concentrations of harmful gaeses and time of year. It is apperent that global warming is a problem due to the harmful gasses and the temperature rises each year.

## References

Your code above should include references.  Here is some additional space for references.

* What is the source of your dataset(s)?

The dataset I downloaded was from Kaggle:
https://www.kaggle.com/datasets/econdata/climate-change

* List any other references that you found helpful.

Lectures notes 12-16, which covers linear regression, polynomial regression, Mean Square Error, train test split

K-Nearest Neighbors Regressor lecture 24:
https://deepnote.com/workspace/Math-10-2026-Spring-dd36c01a-9905-4570-8b22-f572fd5cd400/project/06-03-2026-W-Lecture-24-9ace427b-ffc5-4d5c-8d89-5a67ae427a27/notebook/1-K-Nearest-Neighbors-Regressor-c41b380e6fcc433bad438b4cab321155?utm_source=share-modal&utm_medium=product-shared-content&utm_campaign=notebook&utm_content=9ace427b-ffc5-4d5c-8d89-5a67ae427a27

## Submission

Using the Share button at the top right, **enable Comment privileges** for anyone with a link to the project. Then submit that link on Canvas.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=13dbfdda-a883-4c1d-b8b1-716b9de536cb' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>